### ISSUE TITLE
nanomsgxx can't find nanomsg on Arch

### ISSUE THREAD

**Issue by Ezodev** [achille-roussel/nanomsgxx#12]
Hi. I've installed nanomsg via Pacman, and it works fine. But then I cloned this project, ran ./waf configure, and I've got this:
```

Setting top to                           : /mnt/data/DEV/libs/nanomsgxx 
Setting out to                           : /mnt/data/DEV/libs/nanomsgxx/build 
Checking for 'gcc' (c compiler)          : /usr/bin/gcc 
Checking for 'g++' (c++ compiler)        : /usr/bin/g++ 
Checking for library nanomsg             : Traceback (most recent call last):
  File "/mnt/data/DEV/libs/nanomsgxx/.waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Scripting.py", line 97, in waf_entry_point
    run_commands()
  File "/mnt/data/DEV/libs/nanomsgxx/.waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Scripting.py", line 153, in run_commands
    ctx=run_command(cmd_name)
  File "/mnt/data/DEV/libs/nanomsgxx/.waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Scripting.py", line 146, in run_command
    ctx.execute()
  File "/mnt/data/DEV/libs/nanomsgxx/.waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Configure.py", line 128, in execute
    super(ConfigurationContext,self).execute()
  File "/mnt/data/DEV/libs/nanomsgxx/.waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Context.py", line 87, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/mnt/data/DEV/libs/nanomsgxx/.waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Context.py", line 128, in recurse
    user_function(self)
  File "/mnt/data/DEV/libs/nanomsgxx/wscript", line 51, in configure
    waf.recurse('src/nnxx')
  File "/mnt/data/DEV/libs/nanomsgxx/.waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Context.py", line 128, in recurse
    user_function(self)
  File "/mnt/data/DEV/libs/nanomsgxx/src/nnxx/wscript", line 16, in configure
    waf.check_cxx(lib='nanomsg')
  File "/mnt/data/DEV/libs/nanomsgxx/.waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Configure.py", line 224, in fun
    return f(*k,**kw)
  File "/mnt/data/DEV/libs/nanomsgxx/.waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Tools/c_config.py", line 473, in check_cxx
    return self.check(*k,**kw)
  File "/mnt/data/DEV/libs/nanomsgxx/.waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Configure.py", line 224, in fun
    return f(*k,**kw)
  File "/mnt/data/DEV/libs/nanomsgxx/.waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Tools/c_config.py", line 375, in check
    ret=self.run_c_code(*k,**kw)
  File "/mnt/data/DEV/libs/nanomsgxx/.waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Configure.py", line 224, in fun
    return f(*k,**kw)
  File "/mnt/data/DEV/libs/nanomsgxx/.waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Tools/c_config.py", line 459, in run_c_code
    bld.compile()
  File "/mnt/data/DEV/libs/nanomsgxx/.waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Build.py", line 186, in compile
    self.store()
  File "/mnt/data/DEV/libs/nanomsgxx/.waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Utils.py", line 386, in f
    ret=fun(*k,**kw)
  File "/mnt/data/DEV/libs/nanomsgxx/.waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Build.py", line 162, in store
    x=cPickle.dumps(data,-1)
AttributeError: Can't pickle local object 'Context.__init__.<locals>.node_class'

```

Any idea how to make it work?

**Comment by achille-roussel** [comment]
Seems like it's a crash in the internals of waf, what python version do you run this with?

**Comment by Ezodev** [comment]
`python` yields python 3.5.2 interpreter. I also have python 2.7.12

**Comment by BenjaminNavarro** [comment]
Same problem here, solved by running `python2 waf configure` instead of `./waf configure`
